version: '3.8'
services:
  web:
    image: httpd:latest
    ports:
      - "80:80"
    volumes:
    - ./web:/var/www/html
  php:
    image: php:fpm
    volumes:
      - ./web:/var/www/html
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"

~                     
